### ISSUE TITLE
context menu shortcut_label is invisible

### ISSUE THREAD

**Issue by bleuscyther** [vakata/jstree#1225]
I am sure of the reason for the `display none` if there are other properties like opacity ....
```css
.vakata-context .vakata-contextmenu-shortcut  {
  font-size: 0.8em;
  color: silver;
  opacity: 0.5;
  display: none;
}
````
when i force display it it's a little off,  also i am guessing that it can conflict with the caret of the sub-menu.

I could find no official word on that so i had to post.

Thanks for that Awesome plugin trying it with [PhpRbac](http://phprbac.net/)
