### ISSUE TITLE
Touch support on internet explorer / microsoft surface

### ISSUE THREAD

**Issue by FinalAngel** [vakata/jstree#1326]
I faced an issue where drag & drop did not appear to work on microsoft surface (internet explorer). The solution to this problem is fairly simple, just add:

```css
.jstree li {
    -ms-touch-action: none;
    touch-action: none;
}
```

to your css and it works. It would make sense to update your demos with this css and add a comment to inform developers about it.
