### ISSUE TITLE
Checkboxes - hide checkbox on roots node

### ISSUE THREAD

**Issue by LeonardoChirivi** [vakata/jstree#1532]
I'm trying hard but I've only managed to hide just the first root node whit this:
```jquery
$('.root').find('.jstree-checkbox').remove();
```
Every root I want to hide has class .root, but I keep selecting the very first one
any suggestion?

```jquery
$('#jstree_demo_div')
			.jstree({
				'core' : {'themes': {'icons': false}},
				"plugins" : ["checkbox"]
			});
 ```

**Comment by LeonardoChirivi** [comment]
Nevermind I did it, here's how if may help someone:

```css
.jstree li.jstree-open > a.jstree-anchor > i.jstree-checkbox, 
.jstree li.jstree-closed > a.jstree-anchor > i.jstree-checkbox { 
	display:none; 
}
```
