### ISSUE TITLE
Make tree node bold when hovering over

### ISSUE THREAD

**Issue by YukiPaul** [vakata/jstree#1557]
Hi,

I want to add the following functionality to my jstree: 
When I hover over a node, the node text should be shown in bold. 
I have searched a lot but couldn't find a proper solution for my case.

Any input will be appreciated, thanks in advance.

**Comment by aadrian** [comment]
have you tried using simple CSS for this and was not working? e.g. something like:
```css
li.jstree-node > a.jstree-anchor:hover {
  font-weight: bold;
}
```
http://jsfiddle.net/2kwkh2uL/4551/
