### ISSUE TITLE
Option to remove dots and arrow from root element

### ISSUE THREAD

**Issue by Rikijs** [vakata/jstree#2192]
First, thank you for terrific project!

Though, i see one aspect of the tree that is not accounted for.
(Or i was not able to find this option in documentation).
For my use case i need to remove dots and arrow from root element.

At the moment i use `javascript` and `css` to do just that.
Proof of concept (http://jsfiddle.net/akdLw87c/16/)
It is somewhat clunky. 

Is there better way to display root element of the tree as per my use 
case for `Jstree 3`? Maybe this option could be added to `Jstree 4`?

Thanks for consideration.

**Comment by vakata** [comment]
Thank you for the input.
I am trying to minimize the config options, as they are way too many as it is. What you need can be achieved used pure CSS:
```css
#jstree_demo_div > .jstree-container-ul > .jstree-node > .jstree-ocl { display:none }
#jstree_demo_div > .jstree-container-ul > .jstree-node > .jstree-children > .jstree-node { margin-left:0; }
```
You could create a custom plugin for this if you want - take a look at ```src/misc.js``` for examples, but I won't add it to the core yet. If there is more interest - then I will consider it. Thank you for understanding.
