### ISSUE TITLE
Hide checkbox and dots only for root element

### ISSUE THREAD

**Issue by Rikijs** [vakata/jstree#2241]
Hello!

Building on [previous solutions](https://github.com/vakata/jstree/issues/2192):
-- tree with root and sub elements in multiple levels,
-- with checkbox plugin;

I would like to hide chekbox and dots only for root element of the tree.
What is the best way to do this in this case?
Is it possible with only CSS?

Thank you.

**Comment by vakata** [comment]
Yes - you can target the node using:
```css
.jstree-container-ul > .jstree-node,
.jstree-container-ul > .jstree-node > .jstree-ocl { background:transparent; }
```
You might want to use ```!important``` or a stronger selector if the above does not work for you (like prepend your tree ID to the selectors above).
