### ISSUE TITLE
Use a class instead of a path for icon - DND will get Problems

### ISSUE THREAD

**Issue by Simon83F** [vakata/jstree#2374]
Use a class instead of a path, and in that class define both background and size:

For example:
``` ... "icon": "car" ...```
And in your css:
```css
#mytree .car { background: url(... }
```

_Originally posted by @vakata in https://github.com/vakata/jstree/issues/1890#issuecomment-349615405_
